import { defineAuditConfig } from './src/core/auditConfig.ts';

export default defineAuditConfig({
  name: '@francogp/auditor',
  paths: {
    srcRoots: ['src'],
    testRoots: ['tests'],
    scriptsRoots: ['src/cli'],
    codeRoots: ['src'],
    cliRoots: ['src/cli', 'src/core', 'src/suites', 'src/analyzers'],
    ignoreGlobs: ['node_modules/**', 'dist/**', 'scratch/**', '.agents/**'],
    ignoredDirs: ['skills', '.agents']
  },
  coverage: {
    exemptGlobs: [
      { glob: '.htmlvalidate.json', reason: 'Canonical HTML validation rules engine configuration' },
      { glob: '.markdownlint.json', reason: 'Markdownlint configuration file for repository documentation' },
      { glob: '.markdownlintignore', reason: 'Markdownlint exclusion patterns file for scratch and build dirs' },
      { glob: '.npmrc', reason: 'NPM package manager registry configuration settings' },
      { glob: '.nvmrc', reason: 'Node version manager runtime environment declaration' },
      { glob: '.stylelintrc.json', reason: 'Stylelint configuration file for stylesheet standards' },
      { glob: 'LICENSE', reason: 'MIT software license legal terms and copyright notice' },
      { glob: 'package-lock.json', reason: 'Deterministic npm dependency lockfile generated by npm' },
      { glob: 'plugin.json', reason: 'Antigravity IDE agent plugin schema definition file' },
      { glob: 'setup-linux.sh', reason: 'Linux and macOS environment initialization bootstrap shell script' },
      { glob: 'setup-windows.ps1', reason: 'Windows environment initialization bootstrap PowerShell script' },
      { glob: 'tsconfig.build.json', reason: 'TypeScript compiler configuration for distribution artifacts emission' },
      { glob: 'tsconfig.json', reason: 'TypeScript compiler configuration for root development and testing' }
    ],
    acknowledgedDegradations: [
      { glob: 'src/cli/**', policy: 'cli', reason: 'Command-line execution entrypoints with diagnostic stdout output' },
      { glob: 'src/cli/**', policy: 'scripts', reason: 'Command-line execution runner scripts with intentional console logs' },
      { glob: 'src/core/**', policy: 'cli', reason: 'Core framework runtime engine with diagnostic logging and process controls' },
      { glob: 'src/analyzers/**', policy: 'cli', reason: 'Static analysis calculation modules with diagnostic table rendering' },
      { glob: 'src/suites/**', policy: 'cli', reason: 'Auditor suites and reporting subroutines with console diagnostic output' }
    ]
  },
  persistence: {
    engine: 'none',
    schemaQualified: false
  },
  domain: {
    enabled: false,
    finiteDomainTypes: [],
    infraIdWhitelist: []
  },
  bundle: {
    enabled: false
  },
  styles: {
    zLayersEnabled: false,
    stylelint: {
      enabled: true
    }
  },
  templates: {
    requireInputIds: false
  },
  packageDistribution: {
    enabled: true
  },
  packageHygiene: {
    enabled: true
  },
  accessibility: {
    enabled: false // Herramienta CLI sin vistas SFC Vue interactivas en frontend
  },
  typeCoverage: {
    enabled: true,
    atLeast: 98
  },
  agentPlugin: {
    enabled: true
  },
  documentation: {
    allowedNpxBinaries: ['@modelcontextprotocol/inspector', 'playwright']
  },
  fallow: {
    enabled: true,
    security: {
      enabled: false // Herramienta CLI sin servidores ni endpoints de red
    },
    enforceTargets: false,
    maxTargetPriority: 'critical',
    similarCode: {
      enabled: true,
      threshold: 0.95,
      ignoreSameFile: true
    }
  },
  constants: {
    allowedNumericPrefixes: ['BASE_']
  },
  runner: {
    timeoutMs: 0 // 0 = disabled: permite a todas las suites completar sin timeouts arbitrarios
  },
  presets: {
    commit: [
      'validate_dox_integrity',
      'validate_markdown_syntax',
      'validate_markdown_code_references',
      'validate_markdown_links',
      'validate_markdown_lint',
      'validate_type_check',
      'validate_eslint',
      'validate_console_cleanliness',
      'validate_audit_headers',
      'validate_auditor_tests',
      'validate_test_fragmentation',
      'validate_agent_plugin',
      'validate_bundle_budget',
      'validate_duplicate_constants',
      'validate_ephemeral_storage_isolation'
    ]
  }
});
