#!/usr/bin/env -S node --experimental-strip-types
/**
 * src/cli/bump_version.ts
 *
 * CLI tool for inspecting, analyzing, and applying intelligent SemVer version bumps
 * with build timestamp metadata (@francogp/auditor).
 *
 * Commands:
 *   auditor-version               Print current version and build timestamp
 *   auditor-version analyze       Analyze diff and recommend Major/Minor/Patch
 *   auditor-version bump [type]   Apply version bump (auto|major|minor|patch)
 */

import fs from 'node:fs';
import path from 'node:path';
import { styleText } from 'node:util';
import {
  analyzeVersionBump,
  calculateNextBaseVersion,
  generateBuildId,
  type VersionBumpType,
  type VersionAnalysisResult
} from '../core/versionAnalyzer.ts';
import { AUDITOR_VERSION, AUDITOR_BUILD_ID, AUDITOR_BUILD_DATE } from '../core/version.ts';
import { renderBanner, renderBoxTable, type TableColumn } from '../core/unifiedTheme.ts';
import { getAuditConfig, type AuditEngineConfig, type AuditVersionTargetConfig } from '../core/auditConfig.ts';
import { isMainModule } from './cliUtils.ts';

export interface MetricTableRow {
  readonly label: string;
  readonly value: string;
}

export interface ApplyBumpOptions {
  cwd?: string;
  bumpType?: VersionBumpType | 'auto';
  commitMessage?: string;
  versionTsPath?: string;
  customNow?: Temporal.ZonedDateTime;
  autoSyncPublicVersionJson?: boolean;
  syncTargets?: readonly (string | AuditVersionTargetConfig)[];
}

export interface ApplyBumpResult {
  previousVersion: string;
  newVersion: string;
  bumpType: VersionBumpType;
  buildId: string;
  buildDate: string;
  packageJsonPath: string;
  versionTsPath: string;
  syncedFiles: string[];
}

/**
 * Applies a SemVer bump and persists it to package.json, version.ts, and configured sync targets.
 */
export function applyVersionBump(options: ApplyBumpOptions = {}): ApplyBumpResult {
  const cwd = options.cwd ?? process.cwd();
  const pkgPath = path.join(cwd, 'package.json');

  if (!fs.existsSync(pkgPath)) {
    throw new Error(`package.json not found in ${cwd}`);
  }

  const analysis = analyzeVersionBump({
    cwd,
    commitMessage: options.commitMessage,
    customNow: options.customNow
  });

  const resolvedBump: VersionBumpType = (!options.bumpType || options.bumpType === 'auto')
    ? analysis.recommendedBump
    : options.bumpType;

  const nextBase = calculateNextBaseVersion(analysis.baseVersion, resolvedBump);
  const { buildId, buildDate } = generateBuildId(options.customNow);
  const newVersion = `${nextBase}-build.${buildId}`;
  const syncedFiles: string[] = [pkgPath];

  // Load auditConfig safely if available
  let auditConfig: AuditEngineConfig | null = null;
  try {
    auditConfig = getAuditConfig(cwd);
  } catch {
    // catch-ok: Fallback when audit.config.ts is absent in temp directory
  }

  // 1. Update package.json
  const rawPkg = fs.readFileSync(pkgPath, 'utf-8');
  const pkg = JSON.parse(rawPkg) as { name?: string; version?: string };
  const previousVersion = pkg.version ?? '1.0.0';
  pkg.version = newVersion;
  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`, 'utf-8');

  // 2. Update TypeScript version file only if explicitly configured or inside @francogp/auditor
  const isAuditorPackage = pkg.name === '@francogp/auditor';
  let targetVersionTs = '';

  if (options.versionTsPath || isAuditorPackage) {
    targetVersionTs = options.versionTsPath
      ? path.resolve(cwd, options.versionTsPath)
      : path.resolve(cwd, 'src/core/version.ts');

    const versionTsContent = `/**
 * Single Source of Truth for @francogp/auditor version and build metadata.
 * Automatically generated by auditor-version during compilation.
 */
export const AUDITOR_VERSION = '${newVersion}';
export const AUDITOR_BUILD_ID = '${buildId}';
export const AUDITOR_BUILD_DATE = '${buildDate}';
`;

    try {
      fs.mkdirSync(path.dirname(targetVersionTs), { recursive: true });
      fs.writeFileSync(targetVersionTs, versionTsContent, 'utf-8');
      syncedFiles.push(targetVersionTs);
    } catch {
      // catch-ok: If versionTs cannot be written (e.g. read-only dir), package.json remains updated
    }
  }

  // 3. Resolve and process additional synchronization targets
  const configTargets = options.syncTargets ?? auditConfig?.version?.syncTargets ?? [];
  const normalizedTargets: AuditVersionTargetConfig[] = configTargets.map(t =>
    typeof t === 'string' ? { path: t } : t
  );

  const shouldAutoSyncPublic = options.autoSyncPublicVersionJson ?? auditConfig?.version?.autoSyncPublicVersionJson ?? true;
  const publicVersionPath = path.resolve(cwd, 'public/version.json');

  if (shouldAutoSyncPublic && fs.existsSync(publicVersionPath)) {
    const alreadyDeclared = normalizedTargets.some(t => path.resolve(cwd, t.path) === publicVersionPath);
    if (!alreadyDeclared) {
      normalizedTargets.push({ path: 'public/version.json' });
    }
  }

  for (const target of normalizedTargets) {
    const targetAbsPath = path.resolve(cwd, target.path);
    if (targetAbsPath === pkgPath || targetAbsPath === targetVersionTs) continue;

    const isTs = target.type === 'ts' || target.path.endsWith('.ts');
    try {
      if (isTs) {
        const exportName = target.tsExportName ?? 'APP_VERSION';
        const tsContent = `/**
 * Version and build metadata automatically synchronized by auditor-version.
 */
export const ${exportName} = '${newVersion}';
export const BUILD_ID = '${buildId}';
export const BUILD_DATE = '${buildDate}';
`;
        fs.mkdirSync(path.dirname(targetAbsPath), { recursive: true });
        fs.writeFileSync(targetAbsPath, tsContent, 'utf-8');
        syncedFiles.push(targetAbsPath);
      } else {
        const jsonField = target.jsonField ?? 'version';
        let jsonObj: Record<string, unknown> = {};
        let startsWithV = false;

        if (fs.existsSync(targetAbsPath)) {
          try {
            const rawContent = fs.readFileSync(targetAbsPath, 'utf-8');
            jsonObj = JSON.parse(rawContent) as Record<string, unknown>;
            const currentVal = jsonObj[jsonField];
            if (typeof currentVal === 'string' && currentVal.startsWith('v')) {
              startsWithV = true;
            }
          } catch {
            // catch-ok: Overwrite with fresh JSON if existing was invalid
          }
        }

        const usePrefixV = target.prefixV ?? startsWithV;
        const versionValue = usePrefixV
          ? (newVersion.startsWith('v') ? newVersion : `v${newVersion}`)
          : (newVersion.startsWith('v') ? newVersion.slice(1) : newVersion);

        jsonObj[jsonField] = versionValue;
        fs.mkdirSync(path.dirname(targetAbsPath), { recursive: true });
        fs.writeFileSync(targetAbsPath, `${JSON.stringify(jsonObj, null, 2)}\n`, 'utf-8');
        syncedFiles.push(targetAbsPath);
      }
    } catch {
      // catch-ok: non-fatal if target file cannot be written
    }
  }

  return {
    previousVersion,
    newVersion,
    bumpType: resolvedBump,
    buildId,
    buildDate,
    packageJsonPath: pkgPath,
    versionTsPath: targetVersionTs,
    syncedFiles
  };
}

function renderAnalysisTable(analysis: VersionAnalysisResult): void {
  console.log(renderBanner(
    'AUDITOR VERSION - ANÁLISIS HEURÍSTICO DE VERSIÓN',
    `Versión Actual: ${analysis.currentVersion}  |  Propuesta: ${analysis.recommendedBump.toUpperCase()}`
  ));

  const rows: MetricTableRow[] = [
    { label: 'Versión actual', value: analysis.currentVersion },
    { label: 'Base SemVer detectada', value: analysis.baseVersion },
    { label: 'Salto recomendado', value: styleText('bold', analysis.recommendedBump.toUpperCase()) },
    { label: 'Versión sugerida', value: styleText(['bold', 'green'], analysis.recommendedVersion) },
    { label: 'Justificación', value: analysis.rationale },
    { label: 'Archivos modificados', value: String(analysis.metrics.filesChanged) },
    { label: 'Inserciones / Supresiones', value: `+${analysis.metrics.insertions} / -${analysis.metrics.deletions} (${analysis.metrics.totalLinesChanged} líneas)` },
    { label: 'Impacto en subsistemas', value: `Core: ${analysis.metrics.hasCoreChanges ? 'SÍ' : 'NO'} | Nuevas suites/skills: ${analysis.metrics.hasNewFeatures ? 'SÍ' : 'NO'}` }
  ];

  const columns: TableColumn<MetricTableRow>[] = [
    { header: 'MÉTRICA / PARÁMETRO', width: 28, render: (r: MetricTableRow) => r.label },
    { header: 'DETALLE EVALUADO', width: 46, render: (r: MetricTableRow) => r.value }
  ];

  console.log(renderBoxTable(columns, rows));
  console.log();
}

export function runBumpCli(): void {
  const args = process.argv.slice(2);

  // Fast version query: -v, --version, or bare execution without subcommands
  if (args.length === 0 || args.includes('-v') || args.includes('--version') || args[0] === 'version') {
    console.log(`@francogp/auditor v${AUDITOR_VERSION} (Build: ${AUDITOR_BUILD_ID}, Date: ${AUDITOR_BUILD_DATE})`);
    return;
  }

  const isJson = args.includes('--json');
  const command = args[0]?.toLowerCase();

  if (command === 'analyze' || command === '--analyze') {
    const analysis = analyzeVersionBump();
    if (isJson) {
      console.log(JSON.stringify(analysis, null, 2));
    } else {
      renderAnalysisTable(analysis);
    }
    return;
  }

  if (command === 'bump' || command === '--bump') {
    let bumpType: VersionBumpType | 'auto' = 'auto';
    const typeArg = args.find(a => a.startsWith('--type='));
    if (typeArg) {
      const val = typeArg.split('=')[1]?.toLowerCase();
      if (val === 'major' || val === 'minor' || val === 'patch' || val === 'auto') {
        bumpType = val;
      }
    } else if (args[1] && ['major', 'minor', 'patch', 'auto'].includes(args[1].toLowerCase())) {
      bumpType = args[1].toLowerCase() as VersionBumpType | 'auto';
    }

    const noSyncPublic = args.includes('--no-sync-public');
    const syncArg = args.find(a => a.startsWith('--sync='));
    const syncTargets = syncArg ? syncArg.split('=')[1]?.split(',').filter(Boolean) : undefined;

    const result = applyVersionBump({
      bumpType,
      autoSyncPublicVersionJson: noSyncPublic ? false : undefined,
      syncTargets
    });

    if (isJson) {
      console.log(JSON.stringify(result, null, 2));
    } else {
      console.log(styleText('green', `✔ Versión actualizada exitosamente:`));
      console.log(`  ${result.previousVersion} → ${styleText(['bold', 'cyan'], result.newVersion)} (Salto: ${result.bumpType.toUpperCase()})`);
      const relFiles = result.syncedFiles.map(f => path.relative(process.cwd(), f) || f);
      console.log(`  📄 Archivos sincronizados: ${relFiles.join(', ')}\n`);
    }
    return;
  }

  console.log(`Comando no reconocido: ${command}`);
  console.log(`Uso:`);
  console.log(`  auditor-version               Muestra la versión actual`);
  console.log(`  auditor-version analyze       Analiza el diff y sugiere el salto`);
  console.log(`  auditor-version bump [tipo]   Aplica el salto (auto | major | minor | patch)\n`);
}

if (isMainModule(import.meta.url)) {
  runBumpCli();
}
