/**
 * src/cli/stamp_version.ts
 *
 * Automatically stamps a semver-compliant build timestamp version into package.json
 * and generates src/core/version.ts Single Source of Truth during compilation.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateBuildId, parseBaseSemver } from '../core/versionAnalyzer.ts';
import { isMainModule } from './cliUtils.ts';

export interface StampVersionResult {
  version: string;
  buildId: string;
  buildDate: string;
  packageJsonPath: string;
  versionTsPath: string;
}

/**
 * Generates an elegant build ID and updates package.json and version.ts.
 */
export function stampVersion(projectRoot?: string, customNow?: Temporal.ZonedDateTime): StampVersionResult {
  const root = projectRoot ?? path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../');
  const pkgPath = path.join(root, 'package.json');
  const versionTsPath = path.join(root, 'src/core/version.ts');

  if (!fs.existsSync(pkgPath)) {
    throw new Error(`package.json not found at ${pkgPath}`);
  }

  const rawPkg = fs.readFileSync(pkgPath, 'utf-8');
  const pkg = JSON.parse(rawPkg) as { name?: string; version?: string };

  const currentVersion = pkg.version ?? '1.0.0';
  const [major, minor, patch] = parseBaseSemver(currentVersion);
  const baseVersion = `${major}.${minor}.${patch}`;

  const { buildId, buildDate } = generateBuildId(customNow);
  const version = `${baseVersion}-build.${buildId}`;

  pkg.version = version;
  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`, 'utf-8');

  const versionTsContent = `/**
 * Single Source of Truth for @francogp/auditor version and build metadata.
 * Automatically generated by stamp_version.ts during compilation.
 */
export const AUDITOR_VERSION = '${version}';
export const AUDITOR_BUILD_ID = '${buildId}';
export const AUDITOR_BUILD_DATE = '${buildDate}';
`;

  fs.mkdirSync(path.dirname(versionTsPath), { recursive: true });
  fs.writeFileSync(versionTsPath, versionTsContent, 'utf-8');

  return {
    version,
    buildId,
    buildDate,
    packageJsonPath: pkgPath,
    versionTsPath
  };
}

if (isMainModule(import.meta.url)) {
  const result = stampVersion();
  console.log(`[Version Stamped] ${result.version} (Build: ${result.buildId})`);
}
