/**
 * Single Source of Truth for @francogp/auditor version and build metadata.
 * Automatically generated by auditor-version during compilation.
 */
export const AUDITOR_VERSION = '6.10.0-build.20261010-010955';
export const AUDITOR_BUILD_ID = '20261010-010955';
export const AUDITOR_BUILD_DATE = '2026-10-10T01:09:55.354576904-03:00[America/Buenos_Aires]';
