/**
 * Single Source of Truth for @francogp/auditor version and build metadata.
 * Automatically generated by auditor-version during compilation.
 */
export const AUDITOR_VERSION = '3.1.0-build.20261003-192724';
export const AUDITOR_BUILD_ID = '20261003-192724';
export const AUDITOR_BUILD_DATE = '2026-10-03T19:27:24.691052002-03:00[America/Buenos_Aires]';
