/**
 * Single Source of Truth for @francogp/auditor version and build metadata.
 * Automatically generated by auditor-version during compilation.
 */
export const AUDITOR_VERSION = '4.0.1-build.20261004-220749';
export const AUDITOR_BUILD_ID = '20261004-220749';
export const AUDITOR_BUILD_DATE = '2026-10-04T22:07:49.017896973-03:00[America/Buenos_Aires]';
